name: Publish chart
on:
  release:
    types: [ published ]
uses: appany/helm-oci-chart-releaser@v0.3.0
with:
  name: slack-chatgpt
  repository: emmekappa/slack-chatgpt
  tag: 0.1.0
  #path: charts/slack-chatgpt # Default charts/{name}
  registry: ghcr.io
  registry_username: ${{ secrets.REGISTRY_USERNAME }}
  registry_password: ${{ secrets.REGISTRY_PASSWORD }}